// <auto-generated />
using System;
using GardenerCheatSheet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GardenerCheatSheet.Infrastructure.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260722120000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("GardenerCheatSheet.Domain.Garden.GardenEntry", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<DateOnly>("DateAdded")
                .HasColumnType("TEXT");

            b.Property<string>("ImageUrlOverride")
                .HasColumnType("TEXT");

            b.Property<bool?>("IsIndoorOverride")
                .HasColumnType("INTEGER");

            b.Property<DateOnly?>("LastWatered")
                .HasColumnType("TEXT");

            b.Property<string>("Nickname")
                .HasColumnType("TEXT");

            b.Property<string>("Notes")
                .HasColumnType("TEXT");

            b.Property<int>("PlantId")
                .HasColumnType("INTEGER");

            b.Property<int?>("WateringOverrideDays")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("PlantId");

            b.ToTable("GardenEntries");
        });

        modelBuilder.Entity("GardenerCheatSheet.Domain.Plants.Plant", b =>
        {
            b.Property<int>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("INTEGER");

            b.Property<string>("CommonName")
                .HasColumnType("TEXT");

            b.Property<string>("Family")
                .HasColumnType("TEXT");

            b.Property<string>("ImageUrl")
                .HasColumnType("TEXT");

            b.Property<bool>("IsIndoor")
                .HasColumnType("INTEGER");

            b.Property<string>("ScientificName")
                .IsRequired()
                .HasColumnType("TEXT");

            b.Property<int>("Source")
                .HasColumnType("INTEGER");

            b.Property<int?>("TrefleId")
                .HasColumnType("INTEGER");

            b.HasKey("Id");

            b.HasIndex("TrefleId")
                .IsUnique()
                .HasFilter("\"TrefleId\" IS NOT NULL");

            b.ToTable("Plants");
        });

        modelBuilder.Entity("GardenerCheatSheet.Domain.Plants.Plant", b =>
        {
            b.OwnsOne("GardenerCheatSheet.Domain.Plants.GrowthInfo", "Growth", b1 =>
            {
                b1.Property<int>("PlantId")
                    .HasColumnType("INTEGER");

                b1.Property<int?>("AtmosphericHumidity")
                    .HasColumnType("INTEGER");

                b1.Property<string>("Description")
                    .HasColumnType("TEXT");

                b1.Property<int?>("Light")
                    .HasColumnType("INTEGER");

                b1.Property<int?>("MaximumPrecipitationMm")
                    .HasColumnType("INTEGER");

                b1.Property<int?>("MinimumPrecipitationMm")
                    .HasColumnType("INTEGER");

                b1.Property<string>("SoilTexture")
                    .HasColumnType("TEXT");

                b1.HasKey("PlantId");

                b1.ToTable("Plants");

                b1.WithOwner()
                    .HasForeignKey("PlantId");
            });

            b.Navigation("Growth")
                .IsRequired();
        });

        modelBuilder.Entity("GardenerCheatSheet.Domain.Garden.GardenEntry", b =>
        {
            b.HasOne("GardenerCheatSheet.Domain.Plants.Plant", "Plant")
                .WithMany()
                .HasForeignKey("PlantId")
                .OnDelete(DeleteBehavior.Cascade)
                .IsRequired();

            b.Navigation("Plant");
        });
    }
}
