// <auto-generated />
using System;
using GardenerCheatSheet.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GardenerCheatSheet.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260724125902_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GardenerCheatSheet.Domain.Garden.GardenEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("date");

                    b.Property<string>("ImageUrlOverride")
                        .HasColumnType("text");

                    b.Property<bool?>("IsIndoorOverride")
                        .HasColumnType("boolean");

                    b.Property<DateOnly?>("LastWatered")
                        .HasColumnType("date");

                    b.Property<string>("Nickname")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer");

                    b.Property<int?>("WateringOverrideDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("GardenEntries");
                });

            modelBuilder.Entity("GardenerCheatSheet.Domain.Plants.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CommonName")
                        .HasColumnType("text");

                    b.Property<string>("Family")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsIndoor")
                        .HasColumnType("boolean");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int?>("TrefleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrefleId")
                        .IsUnique()
                        .HasFilter("\"TrefleId\" IS NOT NULL");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("GardenerCheatSheet.Domain.Garden.GardenEntry", b =>
                {
                    b.HasOne("GardenerCheatSheet.Domain.Plants.Plant", "Plant")
                        .WithMany()
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("GardenerCheatSheet.Domain.Plants.Plant", b =>
                {
                    b.OwnsOne("GardenerCheatSheet.Domain.Plants.GrowthInfo", "Growth", b1 =>
                        {
                            b1.Property<int>("PlantId")
                                .HasColumnType("integer");

                            b1.Property<int?>("AtmosphericHumidity")
                                .HasColumnType("integer");

                            b1.Property<string>("Description")
                                .HasColumnType("text");

                            b1.Property<int?>("Light")
                                .HasColumnType("integer");

                            b1.Property<int?>("MaximumPrecipitationMm")
                                .HasColumnType("integer");

                            b1.Property<int?>("MinimumPrecipitationMm")
                                .HasColumnType("integer");

                            b1.Property<string>("SoilTexture")
                                .HasColumnType("text");

                            b1.HasKey("PlantId");

                            b1.ToTable("Plants");

                            b1.WithOwner()
                                .HasForeignKey("PlantId");
                        });

                    b.Navigation("Growth")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
